---
institution_code: 'MIT'
host:             '<%= ENV["MIT_ILLIAD_MSSQL_HOST"] %>'
port:             '<%= ENV["MIT_ILLIAD_MSSQL_PORT"] %>'
database:         '<%= ENV["MIT_ILLIAD_MSSQL_DB"]   %>'
username:         '<%= ENV["MIT_ILLIAD_MSSQL_UID"]  %>'
password:         '<%= ENV["MIT_ILLIAD_MSSQL_PWD"]  %>'
pool:             5
timeout:          5000
export_folder:    '/tmp/mit_illiad/'
batch_size:       10000
