load_sequence:         18.0
target_model:          "Keyserver::Program"
target_adapter:        "console_command"
commands:
  - "rm -rf /tmp/Programs.csv.tmp"
  - "rm -rf /tmp/Programs.cleaned.csv.tmp"
  - "mv /Users/erhanberber/development/NM/docs/metridoc/keyserverexport11082016/Programs.csv /tmp/Programs.csv.tmp"
  - "iconv -f ISO-8859-1 -t UTF-8 /tmp/Programs.csv.tmp > /tmp/Programs.cleaned.csv.tmp "
  - "rm -rf /Users/erhanberber/development/NM/docs/metridoc/keyserverexport11082016/Programs.csv"
  - "mv /tmp/Programs.cleaned.csv.tmp /Users/erhanberber/development/NM/docs/metridoc/keyserverexport11082016/Programs.csv"
