---
institution_code: 'DUKE'
host:             '<%= ENV["DUKE_ILLIAD_MSSQL_HOST"] %>'
port:             '<%= ENV["DUKE_ILLIAD_MSSQL_PORT"] %>'
database:         '<%= ENV["DUKE_ILLIAD_MSSQL_DB"]   %>'
username:         '<%= ENV["DUKE_ILLIAD_MSSQL_UID"]  %>'
password:         '<%= ENV["DUKE_ILLIAD_MSSQL_PWD"]  %>'
pool:             5
timeout:          5000
export_folder:    '/tmp/duke_illiad/'
batch_size:       10000
