load_sequence:         1

# Source Config
source_adapter:        mssql
select_distinct:       true
source_table:          "Groups"
column_mappings:
  GroupNumber: group_no
  GroupName:   group_name
export_file_name:      "groups.csv"

# Target Config
target_adapter:        csv
target_model:          "Illiad::Group"
truncate_before_load:  "yes"
target_mappings:
  group_no: group_no
  group_name: group_name
