load_sequence:         1

# Source Config
source_adapter:        mssql
source_table:          "id_request"
column_mappings:
  "s.library_id": lender
  "p.patron_type": patron_type
  "id_request.library_id": borrower
  "id_request.request_number": request_number
  "id_request.author": author
  "id_request.title": title
  "id_request.local_item_found": local_item_found
  "id_request.publisher": publisher
  "id_request.publication_place": publication_place
  "id_request.publication_year": publication_year
  "id_request.edition": edition
  "id_request.isbn": isbn
  "id_request.isbn_2": isbn_2
  "id_request.bibliography_num": lccn
  "id_request.system_number": oclc_text
  "id_request.date_entered": request_date
  "d.date_processed": process_date
  "pl.pickup_location_desc": pickup_location
  "d.supplier_code_1": supplier_code
  "h.call_number": call_number
join_tables:
  - "LEFT JOIN id_delivery d ON id_request.request_number = d.request_number"
  - "LEFT JOIN id_supplier s ON d.supplier_code_1 = s.supplier_code"
  - "LEFT JOIN id_pickup_location pl ON d.deliv_address=pl.pickup_location AND id_request.library_id = PL.library_id"
  - "LEFT JOIN id_holdings h ON id_request.request_number=h.request_number AND d.supplier_code_1 = h.supplier_code"
filters:
  - "h.holdings_seq_2": "1"
export_file_name:      "bibliographies.csv"

# Target Config
target_adapter:        csv
target_model:          "Borrowdirect::Bibliography"
truncate_before_load:  "yes"
do_validations:        "yes"
