load_sequence:         4

# Source Config
source_adapter:        mssql
source_table:          "id_audit"
column_mappings:
  "id_audit.request_number": request_number
  "id_audit.time_stamp": ship_date
  "id_audit.exception_code": exception_code
  "d.date_processed": process_date 
join_tables:
  - "LEFT JOIN id_delivery d ON id_audit.request_number = d.request_number"
filters:
  - "id_audit.exception_code <> 'NULL'"
export_file_name:      "ship_dates.csv"

# Target Config
target_adapter:        csv
target_model:          "Borrowdirect::ShipDate"
truncate_before_load:  "yes"
