load_sequence:         5

# Source Config
source_adapter:        mssql
source_table:          "id_catalog_code"
column_mappings:
  catalog_code: catalog_code
  catalog_code_desc: institution
  catalog_library_id: library_id
export_file_name:      "institutions.csv"

# Target Config
target_adapter:        csv
target_model:          "Borrowdirect::Institution"
truncate_before_load:  "yes"
