load_sequence:         8
target_adapter:        "native_sql"
target_model:          "Borrowdirect::MinShipDate"
truncate_before_load:  "yes"
sqls:
  - |
                        INSERT INTO borrowdirect_min_ship_dates (
                                request_number,
                                min_ship_date
                        )
                        SELECT S.request_number, S.min_ship_date_shd FROM (
                          SELECT request_number, MIN(ship_date) as min_ship_date_shd
                          FROM borrowdirect_ship_dates shd
                          where shd.ship_date is not null 
                          group by shd.request_number
                        ) S
                        LEFT JOIN borrowdirect_min_ship_dates T ON T.request_number = S.request_number
                        WHERE T.request_number IS NULL
