default: &default
  adapter: postgresql
  
development:
  <<: *default
  database: metridoc_development
  username: metridoc_development
  password: metridoc_development

test:
  <<: *default
  database: metridoc_test
  username: metridoc_test
  password: metridoc_test
