load_sequence:         1
target_model:          "Illiad::Group"
truncate_before_load:  "yes"
select_distinct:       true
source_table:          "Groups"
column_mappings:
  GroupNumber: group_no
  GroupName:   group_name

