load_sequence:         2
target_model:          "Illiad::LenderGroup"
truncate_before_load:  "yes"
select_distinct:       true
source_table:          "GroupsLink"
column_mappings:
  GroupNumber:  group_no
  LenderString: lender_code
