load_sequence:         3
target_model:          "Illiad::LenderInfo"
truncate_before_load:  "yes"
filter:                ""
select_distinct:       true
# select_sql:            "LenderString, LibraryName, loanbillingcategory, address1+'; '+address2+'; '+address3+'; '+address4 AS address"
source_table:          "LenderAddressesALL"
# unique_column:
column_mappings:
  LenderString:         lender_code
  LibraryName:          library_name
  LoanBillingCategory:  billing_category
  "address1+'; '+address2+'; '+address3+'; '+address4 ": address
