load_sequence:         4
target_model:          "Illiad::ReferenceNumber"
truncate_before_load:  "yes"
filters:
  - "Transactions.TransactionStatus": ['Request Finished','Cancelled by ILL Staff']
source_table:           Transactions
join_tables:
  - "INNER JOIN WorldCatInformation I ON I.TransactionNumber = Transactions.TransactionNumber"
column_mappings:
  "I.TransactionNumber": transaction_number
  "I.OCLCNumber": oclc
  "I.Type": ref_type
  "I.Data": ref_number
