load_sequence:         8
target_model:          "Illiad::UserInfo"
truncate_before_load:  "yes"
source_table:           "UsersALL"
column_mappings:
  "UsersALL.status": status
  "UsersALL.department": department
  "UsersALL.nvtgc": nvtgc
filter_raw: |
                        EXISTS (
                          SELECT *
                          FROM  Transactions T
                          WHERE T.username = UsersALL.username
                        )
